const crypto=require('crypto'); const R=require('../repositories/TeamsRepositories'); const {createNotification}=require('../repositories/NotificationRepositories'); const {getIo}=require('../lib/WebSocket');
const { finalizeUploadService }=require('./FileServices');
const ROLES=['Owner','Admin','Manager','Member'], STATUSES=['Active','Invited','Pending','Left','Suspended','Removed'];
class TeamError extends Error{constructor(message,statusCode=400){super(message);this.statusCode=statusCode;}}
const clean=(v,n=500)=>String(v||'').trim().slice(0,n);
const withAvatar=(row)=>{if(!row?.avatar_path||/^https?:\/\//i.test(row.avatar_path))return row;const base=String(process.env.CLOUDFRONT_URL||process.env.AWS_CLOUDFRONT_URL||'').replace(/\/$/,'');return{...row,avatar_path:base?`${base}/${String(row.avatar_path).replace(/^\/+/, '')}`:row.avatar_path};};
async function context(teamId,accountId){const team=await R.getTeam(teamId,accountId);if(!team)throw new TeamError('Team not found',404);const membership=await R.getMembership(teamId,accountId);return{team,membership};}
function permissions(m){const active=m?.status==='Active',role=m?.role;return{can_update_team:active&&['Owner','Admin'].includes(role),can_delete_team:active&&role==='Owner',can_manage_members:active&&['Owner','Admin'].includes(role),can_manage_requests:active&&['Owner','Admin'].includes(role),can_view_wallet:active&&['Owner','Admin'].includes(role),can_chat:active};}
async function create(accountId,userId,b){const name=clean(b.name,50),handle=clean(b.handle,50).replace(/^@/,'');if(!name||!handle||!b.avatarUploadIntentId)throw new TeamError('Name, handle, and team photo are required');const uploaded=await finalizeUploadService(accountId,b.avatarUploadIntentId);return R.createTeam({name,handle,description:clean(b.description,2000),tagline:clean(b.tagline,50),visibility:['Public','Private'].includes(b.visibility)?b.visibility:'Public',joinPolicy:['Open','Approval'].includes(b.joinPolicy)?b.joinPolicy:'Approval',category:clean(b.category,80),website:clean(b.website,500),location:clean(b.location,150),avatarFileId:uploaded.fileId,joinCode:crypto.randomBytes(6).toString('hex').toUpperCase()},userId);}
async function list(accountId,q){return (await R.listTeams(accountId,clean(q.search,100),q.mine==='true',Math.min(+q.limit||20,50),Math.max(+q.offset||0,0))).map(withAvatar);}
async function detail(id,accountId){const {team:rawTeam,membership}=await context(id,accountId),team=withAvatar(rawTeam);if(team.visibility==='Private'&&membership?.status!=='Active')throw new TeamError('Team not found',404);const p=permissions(membership);return{...team,join_code:p.can_manage_members?team.join_code:undefined,current_user_membership:membership?{role:membership.role,status:membership.status,permissions:p}:null};}
async function update(id,accountId,b){const c=await context(id,accountId);if(!permissions(c.membership).can_update_team)throw new TeamError('Not allowed',403);return R.updateTeam(id,c.team.account_id,{name:b.name?clean(b.name,50):null,handle:b.handle?clean(b.handle,50).replace(/^@/,''):null,description:b.description===undefined?null:clean(b.description,2000),tagline:b.tagline===undefined?null:clean(b.tagline,50),visibility:b.visibility,joinPolicy:b.joinPolicy,category:b.category,website:b.website,location:b.location,avatarFileId:b.avatarFileId});}
async function remove(id,a){const c=await context(id,a);if(!permissions(c.membership).can_delete_team)throw new TeamError('Only the owner can delete the team',403);return R.softDeleteTeam(id);}
async function members(id,a,statuses){const c=await context(id,a);if(!c.membership&&c.team.visibility!=='Public')throw new TeamError('Not allowed',403);const allowed=permissions(c.membership).can_manage_members?['Active','Suspended']:['Active'];const requested=Array.isArray(statuses)?statuses.filter(status=>allowed.includes(status)):allowed;return R.listMembers(id,requested.length?requested:allowed);}
async function requests(id,a,q={}){const c=await context(id,a);if(!permissions(c.membership).can_manage_requests)throw new TeamError('Not allowed',403);return R.listJoinRequests(id,clean(q.search,100));}
async function syncChat(id){return R.syncTeamInboxMembers(id,await R.listMembers(id,['Active']));}
function queueChatSync(id){void syncChat(id).catch(error=>console.error(`Team chat sync failed for ${id}:`,error.message));}
async function joinWithStatus(id,a,status){const uid=await R.getUserId(a);if(!uid)throw new TeamError('User not found',404);const c=await context(id,a);if(c.membership?.status==='Suspended')throw new TeamError('Suspended members cannot rejoin',403);if(c.membership?.status==='Active')throw new TeamError('Already a member',409);if(c.membership?.status==='Pending')throw new TeamError('Join request is already pending',409);if(c.membership?.status==='Invited')throw new TeamError('Respond to your existing invitation',409);const result=await R.upsertMembership(id,uid,'Member',status);if(result.status==='Active')queueChatSync(id);return result;}
async function join(id,a){return joinWithStatus(id,a,'Pending');}
async function joinCode(code,a){const t=await R.findByCode(clean(code,32));if(!t)throw new TeamError('Invalid team code',404);return joinWithStatus(t.team_id,a,t.join_policy==='Open'?'Active':'Pending');}
async function manage(id,a,targetAccount,action,value){const c=await context(id,a);if(!permissions(c.membership).can_manage_members)throw new TeamError('Not allowed',403);const target=await R.getMembership(id,targetAccount);if(!target)throw new TeamError('Membership not found',404);if(target.role==='Owner')throw new TeamError('Owner cannot be modified here',403);if(c.membership.role==='Admin'&&target.role==='Admin')throw new TeamError('Admins cannot modify another Admin',403);if(['approve','deny'].includes(action)&&target.status!=='Pending')throw new TeamError('Join request is no longer pending',409);if(action==='role'){if(!ROLES.includes(value)||value==='Owner'||(c.membership.role==='Admin'&&value==='Admin'))throw new TeamError('Invalid role',422);const result=await R.updateMembership(id,target.user_id,{role:value});queueChatSync(id);return result;}const map={approve:'Active',deny:'Removed',suspend:'Suspended',restore:'Active',remove:'Removed'};const result=await R.updateMembership(id,target.user_id,{status:map[action]});queueChatSync(id);return result;}
async function invite(id,a,target,role='Member'){const c=await context(id,a);if(!permissions(c.membership).can_manage_members)throw new TeamError('Not allowed',403);if(!ROLES.includes(role)||role==='Owner')throw new TeamError('Invalid role',422);const uid=await R.getUserId(target);if(!uid)throw new TeamError('User not found',404);return R.upsertMembership(id,uid,role,'Invited',a);}
async function invitation(id,a,accept){const m=await R.getMembership(id,a);if(m?.status!=='Invited')throw new TeamError('Invitation not found',404);const result=await R.updateMembership(id,m.user_id,{status:accept?'Active':'Removed'});queueChatSync(id);return result;}
async function leave(id,a){const m=await R.getMembership(id,a);if(m?.status!=='Active')throw new TeamError('Active membership not found',404);if(m.role==='Owner')throw new TeamError('Transfer ownership before leaving',409);const result=await R.updateMembership(id,m.user_id,{status:'Left'});queueChatSync(id);return result;}
async function transfer(id,a,target){const c=await context(id,a);if(c.membership?.role!=='Owner'||c.membership.status!=='Active')throw new TeamError('Only the owner can transfer ownership',403);const t=await R.getMembership(id,target);if(t?.status!=='Active')throw new TeamError('Target must be active',422);await R.transferOwnership(id,c.membership.user_id,t.user_id);}
async function wallet(id,a){const c=await context(id,a);if(!permissions(c.membership).can_view_wallet)throw new TeamError('Not allowed',403);return R.wallet(id);}
async function transactions(id,a,query){const c=await context(id,a);if(!permissions(c.membership).can_view_wallet)throw new TeamError('Not allowed',403);return R.getTeamTransactions(id,query);}
async function distributeFunds(id,a,recipients){const c=await context(id,a);if(c.membership?.role!=='Owner'||c.membership.status!=='Active')throw new TeamError('Only the active Team owner can distribute Team funds',403);if(!Array.isArray(recipients)||recipients.length<1||recipients.length>100)throw new TeamError('Select one or more Team members',422);const seen=new Set(),normalized=recipients.map((recipient)=>{const accountId=String(recipient?.account_id||'');const credits=Number(recipient?.amount_credits);if(!accountId||!Number.isSafeInteger(credits)||credits<=0)throw new TeamError('Each distribution requires a member and whole-credit amount',422);if(seen.has(accountId))throw new TeamError('A Team member can only be included once per distribution',422);seen.add(accountId);return{account_id:accountId,amount_credits:credits};});const result=await R.distributeTeamFunds(id,normalized),io=getIo();for(const transaction of result.transactions){const recipient=await R.getMembership(id,transaction.recipient_account_id);const recipientName=recipient?.display_name||'a Team member';const recipientNotification=await createNotification({message:`You have received ${transaction.amount_credits} credits from Team ${c.team.display_name}.`,is_read:false,reference_table:'credit_transactions',reference_prefix:'TEAM_FUND_TRANSFER',reference_path:`/teams/${id}`,reference_id:transaction.credit_transaction_id,account_id:transaction.recipient_account_id});io.to(String(transaction.recipient_account_id)).emit('notification',recipientNotification);const ownerNotification=await createNotification({message:`${transaction.amount_credits} credits transferred to ${recipientName} from Team ${c.team.display_name}.`,is_read:false,reference_table:'credit_transactions',reference_prefix:'TEAM_FUND_TRANSFER',reference_path:`/teams/${id}`,reference_id:transaction.credit_transaction_id,account_id:a});io.to(String(a)).emit('notification',ownerNotification);}return result;}
async function marketplacePosts(id,a,type){const c=await context(id,a);if(c.team.visibility==='Private'&&c.membership?.status!=='Active')throw new TeamError('Team not found',404);if(!['jobs','gigs'].includes(type))throw new TeamError('Marketplace post type must be jobs or gigs',422);return R.listMarketplacePosts(id,type);}async function review(id,a,b){if(+b.rating<1||+b.rating>5)throw new TeamError('Rating must be 1 to 5',422);const c=await context(id,a);if(c.team.account_id===a)throw new TeamError('Cannot review your own team',403);return R.addReview(id,a,{...b,rating:+b.rating});}
async function report(id,a,b){if(!clean(b.category)||!clean(b.description))throw new TeamError('Category and description are required',422);return R.addReport(id,a,{category:clean(b.category,100),description:clean(b.description,2000)});}
async function chat(id,a){const c=await context(id,a);if(c.membership?.status!=='Active')throw new TeamError('Only active members can open Team Chat',403);let inbox=await R.getTeamInbox(id);if(!inbox)inbox=await R.createTeamInbox(c.team,await R.listMembers(id,['Active']));else inbox=await syncChat(id);return{conversationId:String(inbox._id)};}
module.exports={TeamError,create,list,detail,update,remove,members,requests,join,joinCode,manage,invite,invitation,leave,transfer,wallet,transactions,distributeFunds,marketplacePosts,reviews:R.reviews,review,report,chat,permissions,STATUSES};
