const r=require('express').Router(),c=require('../controllers/TeamsControllers'),tasks=require('../controllers/TeamTaskControllers'),check=require('../middleware/CheckSession'),auth=require('../middleware/RequireAuth');r.use(check,auth);
r.get('/marketplace-actors',c.marketplaceActors);
r.post('/:teamId/chat',c.chat);
r.get('/:teamId/marketplace-posts',c.marketplacePosts);
r.get('/:teamId/task-workspaces',tasks.list);
r.get('/:teamId/task-workspaces/:contractId',tasks.detail);
r.post('/:teamId/task-workspaces/:contractId/members',tasks.addMembers);
r.delete('/:teamId/task-workspaces/:contractId/members/:memberAccountId',tasks.removeMember);
r.post('/:teamId/task-workspaces/:contractId/tasks',tasks.createTask);
r.patch('/:teamId/task-workspaces/:contractId/tasks/:taskId',tasks.updateTask);
r.delete('/:teamId/task-workspaces/:contractId/tasks/:taskId',tasks.deleteTask);
r.post('/',c.create);r.get('/',c.list);r.post('/join-by-code',c.joinCode);r.get('/:teamId',c.detail);r.patch('/:teamId',c.update);r.delete('/:teamId',c.remove);r.get('/:teamId/members',c.members);r.get('/:teamId/requests',c.requests);r.post('/:teamId/join',c.join);r.post('/:teamId/leave',c.leave);r.post('/:teamId/invitations',c.invite);r.patch('/:teamId/invitations/accept',c.acceptInvite);r.patch('/:teamId/invitations/decline',c.declineInvite);r.patch('/:teamId/requests/:memberAccountId/approve',c.manage('approve'));r.patch('/:teamId/requests/:memberAccountId/deny',c.manage('deny'));r.patch('/:teamId/members/:memberAccountId/role',c.manage('role'));r.patch('/:teamId/members/:memberAccountId/suspend',c.manage('suspend'));r.patch('/:teamId/members/:memberAccountId/restore',c.manage('restore'));r.delete('/:teamId/members/:memberAccountId',c.manage('remove'));r.patch('/:teamId/transfer-ownership',c.transfer);r.get('/:teamId/wallet',c.wallet);r.get('/:teamId/transactions',c.transactions);r.post('/:teamId/wallet/distributions',c.distributeFunds);r.get('/:teamId/reviews',c.reviews);r.post('/:teamId/reviews',c.review);r.post('/:teamId/reports',c.report);module.exports=r;
